[ bots ]
  [ bots.discord ]
  token = "REDACTED"
  enabled=false

  [ bots.telegram ]
  token="REDACTED"
  enabled=false

[ database ]
path = "db/linkmc.db"

[ twitter ]
api_key="ethan is a fucking loser"
api_secret=""

[ web ]
host="localhost:8080"
callback_path="/verify"
# this is used for verifying that requests are coming from our servers
auth_token = "something super secret and secure that no one can guess"

[ discord ]
channel="verify"

[ telegram ]
channel="@mcteamsnews"